--- 
clone: 
  depth: 1
kind: pipeline
name : Nexus Alioth
version: alioth
steps:
 - name: Nexus Alioth
   image: nexgang/ubuntu:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - /noclone3 bash build.sh null alioth lto

